# Generated by Django 5.2 on 2025-04-24 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('found_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('FOUND', 'Found'), ('PENDING', 'Pending Claim'), ('CLAIMED', 'Claimed'), ('ARCHIVED', 'Archived')], default='FOUND', max_length=10)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='id_docs/')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('verification_doc', models.FileField(upload_to='verification_docs/')),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='found.founditem')),
            ],
        ),
    ]
