"""
Django settings for discourse project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Post editing configuration
POST_EDIT_WINDOW_MINUTES = 2  # Global default edit window in minutes

# Post editing configuration
POST_EDIT_WINDOW_MINUTES = 2  # Global default edit window in minutes

# Post editing configuration
POST_EDIT_WINDOW_MINUTES = 2  # Global default edit window in minutes

# Post editing configuration
POST_EDIT_WINDOW_MINUTES = 2  # Global default edit window in minutes

# Post editing configuration
POST_EDIT_WINDOW_MINUTES = 2  # Global default edit window in minutes

# Post editing configuration
POST_EDIT_WINDOW_MINUTES = 2  # Global default edit window in minutes

# Post editing configuration
POST_EDIT_WINDOW_MINUTES = 2  # Global default edit window in minutes

# Post editing configuration
POST_EDIT_WINDOW_MINUTES = 2  # Global default edit window in minutes

# Post editing configuration
POST_EDIT_WINDOW_MINUTES = 2  # Global default edit window in minutes

# Edit window configuration
POST_EDIT_WINDOW_MINUTES = 2  # Default global edit window
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Flag to indicate if we're running tests
TESTING = 'test' in sys.argv

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z*jtnok=hl*y+8a7c&4rn$r2@xoa!hx&ujp6$ucxy&-hn!y&-9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'topic.apps.TopicConfig',
    'post.apps.PostConfig',
    'found.apps.FoundConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'discourse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'discourse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'discourse',
        'USER': 'root',
        'PASSWORD': 'dblapuredemo123',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {'init_command':"set sql_mode='strict_trans_tables'"},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email configuration (development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Authentication settings
LOGIN_REDIRECT_URL = '/topics/'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/topics/create/'  # Redirect to topic creation page after logout

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# FR-PE-005: Global post edit window (2 minutes default)
POST_EDIT_WINDOW_MINUTES = 2
