# Generated by Django 5.2 on 2025-04-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_edit_window_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Category-specific edit window in minutes (overrides global setting)', null=True),
        ),
    ]
