# Generated by Django 5.2 on 2025-04-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_category_post_edit_window_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
